export const prismMapping = {
  html: 'markup',
  xml: 'markup',
  svg: 'markup',
  mathml: 'markup',
  sh: 'bash',
  bash: 'bash',
  bats: 'bash',
  cgi: 'bash',
  fcgi: 'bash',
  command: 'bash',
  ksh: 'bash',
  tmux: 'bash',
  tool: 'bash',
  zsh: 'bash',
  c: 'c',
  h: 'clike',
  cats: 'c',
  idc: 'c',
  w: 'c',
  cpp: 'cpp',
  cc: 'cpp',
  cp: 'cpp',
  cxx: 'cpp',
  hh: 'cpp',
  hpp: 'cpp',
  hxx: 'cpp',
  inl: 'cpp',
  ipp: 'cpp',
  tcc: 'cpp',
  tpp: 'cpp',
  'c++': 'cpp',
  'h++': 'cpp',
  css: 'css',
  js: 'javascript',
  _js: 'javascript',
  bones: 'javascript',
  es6: 'javascript',
  frag: 'javascript',
  gs: 'javascript',
  jake: 'javascript',
  jsb: 'javascript',
  jsfl: 'javascript',
  jsm: 'javascript',
  jss: 'javascript',
  njs: 'javascript',
  pac: 'javascript',
  sjs: 'javascript',
  ssjs: 'javascript',
  xsjs: 'javascript',
  xsjslib: 'javascript',
  jsx: 'jsx',
  coffee: 'coffeescript',
  _coffee: 'coffeescript',
  cjsx: 'coffeescript',
  cson: 'coffeescript',
  iced: 'coffeescript',
  as: 'actionscript',
  diff: 'diff',
  patch: 'diff',
  dockerfile: 'docker',
  ex: 'elixir',
  exs: 'elixir',
  erl: 'erlang',
  es: 'erlang',
  escript: 'erlang',
  hrl: 'erlang',
  git: 'git',
  go: 'go',
  graphql: 'graphql',
  handlebars: 'handlebars',
  hbs: 'handlebars',
  hs: 'haskell',
  hsc: 'haskell',
  java: 'java',
  json: 'json',
  lock: 'json',
  tex: 'latex',
  less: 'less',
  mak: 'makefile',
  d: 'makefile',
  mk: 'makefile',
  md: 'markdown',
  markdown: 'markdown',
  mkd: 'markdown',
  mkdn: 'markdown',
  mkdown: 'markdown',
  ron: 'markdown',
  m: 'objectivec',
  ml: 'ocaml',
  eliom: 'ocaml',
  eliomi: 'ocaml',
  ml4: 'ocaml',
  mli: 'ocaml',
  mll: 'ocaml',
  mly: 'ocaml',
  php: 'php',
  aw: 'php',
  ctp: 'php',
  php3: 'php',
  php4: 'php',
  php5: 'php',
  phpt: 'php',
  py: 'python',
  gyp: 'python',
  lmi: 'python',
  pyde: 'python',
  pyp: 'python',
  pyt: 'python',
  pyw: 'python',
  tac: 'python',
  wsgi: 'python',
  xpy: 'python',
  re: 'reason',
  rb: 'ruby',
  builder: 'ruby',
  gemspec: 'ruby',
  god: 'ruby',
  irbrc: 'ruby',
  jbuilder: 'ruby',
  mspec: 'ruby',
  pluginspec: 'ruby',
  podspec: 'ruby',
  rabl: 'ruby',
  rake: 'ruby',
  rbuild: 'ruby',
  rbw: 'ruby',
  rbx: 'ruby',
  ru: 'ruby',
  ruby: 'ruby',
  thor: 'ruby',
  watchr: 'ruby',
  rs: 'rust',
  sass: 'sass',
  scss: 'scss',
  sql: 'sql',
  cql: 'sql',
  ddl: 'sql',
  prc: 'sql',
  tab: 'sql',
  udf: 'sql',
  viw: 'sql',
  styl: 'stylus',
  swift: 'swift',
  ts: 'typescript',
  tsx: 'jsx',
  vim: 'vim',
  yml: 'yaml',
  reek: 'yaml',
  rviz: 'yaml',
  yaml: 'yaml',
}

// These are the languages that is included in prism-react-renderer
// module.exports = {
//   markup: true,
//   bash: true,
//   clike: true,
//   c: true,
//   cpp: true,
//   css: true,
//   javascript: true,
//   jsx: true,
//   coffeescript: true,
//   actionscript: true,
//   'css-extras': true,
//   diff: true,
//   docker: true,
//   elixir: true,
//   erlang: true,
//   git: true,
//   go: true,
//   graphql: true,
//   handlebars: true,
//   haskell: true,
//   java: true,
//   json: true,
//   latex: true,
//   less: true,
//   makefile: true,
//   markdown: true,
//   objectivec: true,
//   ocaml: true,
//   php: true,
//   'php-extras': true,
//   python: true,
//   reason: true,
//   ruby: true,
//   rust: true,
//   sass: true,
//   scss: true,
//   sql: true,
//   stylus: true,
//   swift: true,
//   typescript: true,
//   vim: true,
//   yaml: true,
// }
