export default [
  {
    depth: 0,
    name: 'QmbxgBtEDUMW9UU2FpP7kmGh5eqfL2mvdiX2cz9WDswuGs',
    path: 'QmbxgBtEDUMW9UU2FpP7kmGh5eqfL2mvdiX2cz9WDswuGs',
    size: 753,
    content: undefined,
    type: 'dir',
  },
  {
    depth: 1,
    name: 'dir',
    path: 'QmbxgBtEDUMW9UU2FpP7kmGh5eqfL2mvdiX2cz9WDswuGs/dir',
    size: 586,
    type: 'dir',
  },
  {
    depth: 2,
    name: 'sub',
    path: 'QmbxgBtEDUMW9UU2FpP7kmGh5eqfL2mvdiX2cz9WDswuGs/dir/sub',
    size: 125,
    type: 'dir',
  },
  {
    depth: 3,
    name: 'sub.md',
    path: 'QmbxgBtEDUMW9UU2FpP7kmGh5eqfL2mvdiX2cz9WDswuGs/dir/sub/sub.md',
    size: 72,
    type: 'file',
  },
  {
    depth: 2,
    name: 'sub2',
    path: 'QmbxgBtEDUMW9UU2FpP7kmGh5eqfL2mvdiX2cz9WDswuGs/dir/sub2',
    size: 116,
    type: 'dir',
  },
  {
    depth: 3,
    name: 'sub2.md',
    path: 'QmbxgBtEDUMW9UU2FpP7kmGh5eqfL2mvdiX2cz9WDswuGs/dir/sub2/sub2.md',
    size: 63,
    type: 'file',
  },
  {
    depth: 2,
    name: 'test_1.md',
    path: 'QmbxgBtEDUMW9UU2FpP7kmGh5eqfL2mvdiX2cz9WDswuGs/dir/test_1.md',
    size: 74,
    type: 'file',
  },
  {
    depth: 2,
    name: 'test_2.md',
    path: 'QmbxgBtEDUMW9UU2FpP7kmGh5eqfL2mvdiX2cz9WDswuGs/dir/test_2.md',
    size: 74,
    type: 'file',
  },
  {
    depth: 1,
    name: 'test.md',
    path: 'QmbxgBtEDUMW9UU2FpP7kmGh5eqfL2mvdiX2cz9WDswuGs/test.md',
    size: 68,
    type: 'file',
  },
]
